config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('notes/', include('my_notes.urls')),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'games'

urlpatterns = [
    path('', TemplateView.as_view(template_name='base_games.html'), name='games'),
]

my_notes/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'my_notes'

urlpatterns = [
    #path('', TemplateView.as_view(template_name='base_my_notes.html'), name='my_notes'),
    path('', views.section_list, name='my_notes'),
    path('<int:section_id>/', views.section_list, name='section_detail'),
    #path('cat/note/', TemplateView.as_view(template_name='note.html'), name='my_notes'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body data-user-background-color="{{ user_background_color }}">
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}"><i class="bi bi-house"></i> <span class="nav-item-text">Strona główna</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/"><i class="bi bi-gear"></i> <span class="nav-item-text">Admin</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'my_notes:my_notes' %}"><i class="bi bi-file-earmark-text"></i> <span class="nav-item-text">Notes</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_detail' %}"><i class="bi bi-person-circle"></i> <span class="nav-item-text">Account</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}"><i class="bi bi-box-arrow-right"></i> <span class="nav-item-text">Log out</span></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-box-arrow-in-right"></i> <span class="nav-item-text">Log in</span></a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}"><i class="bi bi-person-plus"></i> <span class="nav-item-text">Sign up</span></a>
                        </li>
                    {% endif %}
                </ul>
                {% if request.user.is_authenticated %}
                    <span class="navbar-text">
                        <img src="{{ request.user.avatar.url }}" alt="{{ request.user.username }}" class="navbar-avatar">
                        {{ request.user.username }}
                    </span>
                {% endif %}
            </div>
        </div>
    </nav>
<main>
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% block content %}{% endblock %}
</main>
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="{% static 'base.js' %}"></script>

{% endblock scripts %}
{% block extra_js %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Strona główna{% endblock %}

{% block content %}
<h1>Strona główna</h1>
{% endblock %}